sudo: required

matrix:
    include:
        - os: linux
          dist: xenial
          language: python
          python: 3.5
        - os: osx
          osx_image: xcode8.3
          language: generic

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./test/dependencies_osx.sh     ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/dependencies_linux.sh ; fi
    - sudo ./test/tests.sh

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash) ; fi  # Uploading python report to CodeCov 

    #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ${TRAVIS_BUILD_DIR}/sdk/cpp/core/build ; fi
    #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lcov --directory . --capture --output-file coverage.info ; fi # capture coverage info
    #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lcov --remove coverage.info '/usr/*' '/Applications/*' --output-file coverage.info ; fi # filter out system
    #- lcov --list coverage.info #debug info
    # Uploading cpp report to CodeCov
    #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports" ; fi
